src/dashboard/urls.py
from django.urls import path, re_path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('courses/<int:course_id>', views.dashboard, name='course_detail'),
    path('courses', views.course_list, name='course_list'),
]

src/feedback_form/urls.py
from django.urls import path, re_path
from . import views

app_name = 'feedback_form'
urlpatterns = [
    re_path(r'^$', views.feedback_form, name='home'),
]

src/web_demo/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    re_path(r'^dashboard/', include('dashboard.urls')),
    re_path(r'^feedback/', include('feedback_form.urls')),
    path('admin/', admin.site.urls),
]

src/dashboard/models.py
from django.db import models

# Create your models here.

src/feedback_form/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=50)
    location = models.CharField(max_length=30)
    degree = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Feedback(models.Model):
    student_name = models.CharField(max_length=50)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    grade = models.FloatField()
    ranking_level = models.IntegerField()

    def __str__(self):
        return self.student_name

src/feedback_form/forms.py
from django import forms
from .models import Feedback
from .models import Course
from django.core.validators import MaxValueValidator, MinValueValidator

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = "__all__"

    def clean(self):
        print('cleaning')
        data = self.cleaned_data
        if data['grade'] < 0 or data['grade'] > 6:
            raise forms.ValidationError('Grade must be numbers between 0.0 to 6.0')
        elif data['ranking_level'] < 0 or data['ranking_level'] > 5:
            raise forms.ValidationError('Ranking must be numbers between 0 to 5')
        return self.cleaned_data

src/dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from feedback_form.models import Feedback
from feedback_form.models import Course

# Create your views here.

def course_list(request):
    courses = Course.objects.all().values()
    template = loader.get_template('courses.html')

    context = {
        'courses': courses
    }
    return HttpResponse(template.render(context, request))

def dashboard(request, course_id):
    course_name = Course.objects.get(pk=course_id)
    print(course_name)
    feedback_data = Feedback.objects.filter(course_id=course_id).values()
    template = loader.get_template('dashboard.html')
    ranking = [0] * 6
    grade = [0] * 7

    for record in feedback_data:
        ranking[int(record['ranking_level'])] += 1
        grade[int(record['grade'])] += 1

    context = {
        'course_name':course_name,
        'ranking': ranking,
        'grade' : grade,
        'feedback': feedback_data
    }
    return HttpResponse(template.render(context, request))

src/feedback_form/views.py
from django.shortcuts import render
from .forms import FeedbackForm

# Create your views here.
def feedback_form(request):
    error = ""
    if request.method == 'POST':
        form = FeedbackForm(request.POST)

        if form.is_valid():
            form.save()
            return render(request, 'feedback_form/received_form.html')
        else:
            error = "Invalid field value detected, please fix it before submitting"

    else:
        form = FeedbackForm()
    return render(request, 'feedback_form/feedback_form.html', {'form': form, 'error': error})

src/dashboard/templates/courses.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"></head>
<body>
    <table class="table mt-5">
        <thead>
          <tr>
            <th scope="col">Course Name</th>
            <th scope="col">Location</th>
            <th scope="col">Degree</th>
            <th scopr="col">Ranking</th>
          </tr>
        </thead>
        <tbody>
            {% for element in courses %}
            <tr>
                <td>{{ element.name }}</td>
                <td>{{ element.location }}</td>
                <td>{{ element.degree }}</td>
                <td><a href="{% url 'dashboard:course_detail' course_id=element.id %}">See Ranking Graph</a></td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
      <div class="mt-5 ml-3">
        <a href="{% url 'feedback_form:home'%}" class="link-primary">Fill out a course feedback form for us!</a>
      </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

src/dashboard/templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"></head>
</head>
<body>
    <div class="mt-5 ml-5">
      <h2 class="text-muted"> {{course_name}} </h1>
      <hr/>
  </div>
  <div class="row justify-content-md-center">

    <div class="col-5 mr-5">
        <canvas id="ranking"></canvas>
    </div>
    <div class="col-5">
        <canvas id="grade"></canvas>
    </div>
  </div>
  <div class="ml-5">
    <a href="{% url 'dashboard:course_list'%}" class="link-primary">Back to course list</a>
  </div>

  {{ ranking|json_script:"ranking_list" }}
    {{ grade|json_script:"grade_list" }}
    <script>
        const ranking_list = JSON.parse(document.getElementById('ranking_list').textContent);
        const labels_ranking = [
          '0',
          '1',
          '2',
          '3',
          '4',
          '5',
        ];
      
        const data_ranking = {
          labels: labels_ranking,
          datasets: [{
            label: 'Course Ranking',
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(255, 159, 64, 0.2)',
                'rgba(255, 205, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(201, 203, 207, 0.2)'
            ],
            borderColor: [
                'rgb(255, 99, 132)',
                'rgb(255, 159, 64)',
                'rgb(255, 205, 86)',
                'rgb(75, 192, 192)',
                'rgb(54, 162, 235)',
                'rgb(153, 102, 255)',
                'rgb(201, 203, 207)'
            ],
            borderWidth: 1,
            data: ranking_list,
            options:{ 
              scales: {
                y: {
                    ticks: {
                        precision: 0
                    }
                }
              }
            }
          }]
        };
      
        const config_ranking = {
          type: 'bar',
          data: data_ranking,
          options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
          }
        };

        const grade_list = JSON.parse(document.getElementById('grade_list').textContent);
        const labels_grade = [
          '[0.0-1.0)',
          '[1.0-2.0)',
          '[2.0-3.0)',
          '[3.0-4.0)',
          '[4.0-5.0)',
          '[5.0-6.0)',
          '6.0'
        ];
      
        const data_grade = {
          labels: labels_grade,
          datasets: [{
            label: 'Grade Distribution',
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(255, 159, 64, 0.2)',
                'rgba(255, 205, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(201, 203, 207, 0.2)'
            ],
            borderColor: [
                'rgb(255, 99, 132)',
                'rgb(255, 159, 64)',
                'rgb(255, 205, 86)',
                'rgb(75, 192, 192)',
                'rgb(54, 162, 235)',
                'rgb(153, 102, 255)',
                'rgb(201, 203, 207)'
            ],
            borderWidth: 1,
            data: grade_list,
          }]
        };
      
        const config_grade = {
          type: 'bar',
          data: data_grade,
          options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
          }
        };

        const ranking = new Chart(
          document.getElementById('ranking'),
          config_ranking
        );
        const grade = new Chart(
          document.getElementById('grade'),
          config_grade
        );
      </script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>        

src/feedback_form/templates/feedback_form/base.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block body %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

src/feedback_form/templates/feedback_form/feedback_form.html
{% extends 'feedback_form/base.html' %}

{% block title %}Feedback Form{% endblock %}

{% block body %}

{% load crispy_forms_tags %} 

<form action="{% url 'feedback_form:home' %}" method="POST" class="row justify-content-md-center">
    {% csrf_token %}
    <div class="col-10 mt-5">
        <h2 class="text-muted"> Course Feedback Form </h1>
        <hr/>
    </div>
    <div class="col-10  mt-3">
        {{ form.student_name|as_crispy_field }}
    </div>
    <div class="col-10">
        {{ form.course|as_crispy_field }}
    </div>
    <div class="col-10">
        {{ form.grade|as_crispy_field }}
        <p style="font-size:70%; color:grey;">Grade must be numbers between 0-6</p>
    </div>
    <p></p>
    <div class="col-10">
        {{ form.ranking_level|as_crispy_field }}
        <p style="font-size:70%; color:grey;">Ranking must be integers between 0-5</p>
    </div>
    <div class="col-10">
        <p style= "color:red;">{{ error }}</p>
    </div>
    <div class="col-10">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endblock %}

src/feedback_form/templates/feedback_form/received_form.html
{% extends 'feedback_form/base.html' %}

{% block title %}Thanks{% endblock %}

{% load crispy_forms_tags %} 
{% block body %}
<div  class="row justify-content-md-center">
    <div class="col-10 mt-5">
        <h2 class="text-muted"> Thanks for your feedback! </h1>
        <a href="{% url 'dashboard:course_list'%}" class="link-primary">Back to course list</a>
    </div>
</div>
{% endblock %}